script: |
            cd ~/app
            echo "DB_PASS=${{ secrets.DB_PASS }}" > .env
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env

            # Pastikan DB jalan dulu
            docker compose up -d db
            echo "⏳ Waiting for MariaDB to be ready..."
            sleep 15

            # Deploy web dinamis & nginx
            docker pull hakim0901/web_dinamis:latest
            docker compose up -d --no-deps --force-recreate web_dinamis nginx
            docker image prune -f
            echo "✅ Web Dinamis deployed successfully!"